### ISSUE TITLE
Media essentials contents

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-edid-connection-management#32] opened 2021-02-25 15:15 UTC
1. Should it be an array?
2. Should it have additional EDID fields or the whole EDID?

**Comment by prince-chrismc** [comment] 2021-02-25 15:18
* HDCP Support uin described in the EDID
   * To be confirmed in the EDID spec we will refer to? _Not seen_
* Is the set XOR'd by the device, controller or both?

**Comment by andrewstarks** [comment] 2021-03-04 00:42
> Is the set XOR'd by the device, controller, or both?

Below is a really long answer to this question. 

> **Note:** **TL;DR...** Both, and because resources are exposed on the network, any controller can access those resources (provided authentication and security), connections are dynamic, events from the Source/Sender and Destination/Receiver need to be handled, and the aggregate of connected Destination/Receivers matters, I see a need for an interoperable mechanism to represent the media presentation session. I think that IS-XX is in the right spot for this.

In IS 05, when the application requests a connection, there is no verification that the connection was successful in the response (?), and there is nothing that happens if/when the connection is broken. Everything is presumed to be static. The Broadcast (hereinafter System) Controller is in charge. (I believe that this current situation is considered to have gaps.)

In Pro AV use cases, and also possibly ones in production environments, things might be managed, or not. There could potentially be multiple apps that are capable of browsing an RDS registry, or there might not be a registry.

Also, we are dealing with and emulating the behavior familiar to anyone using HDMI/DisplayPort/DVI base band connections, where things are dynamic. The source may change the mode at any time (InfoFrames). The monitor may be unplugged and replugged in (HPD), or the monitor may simulate this event when it needs to change its EDID to restrict or enable a mode, like enabling/disable HDR or a similar setting. Things get exponentially more complicated when multiple monitors are added, especially if they can be added from multiple controllers on the network.

There are two main issues:

1. What is the beginning and end of a connection? When the Flow can be broken and remade (HPD/InfoFrames/etc.)?

2. What is it that controls this session? Or to put it another way, what resource contains the context for this connection?

For question 1, the start of when devices should respond to these events seems to be when the IS-04 command is issued, but where is the end? Is there an NMOS disconnect command? Does disconnection happen when the user unplugs the laptop or monitor? What owns that start/end decision?

The second question follows from the first. Applications that attempt to make connections with Senders that are responding to events from display devices need an interoperable way of aggregating the connected receivers and the sender to coordinate their events under one resource. We can't assume that there is only one System Controller that "knows all" and has the only policy that a device will be asked to respond to.

> **Use Case:** I'm an employee and I am sitting in the back of a large conference room. Someone has put a spreadsheet up on the screen and the text is small enough that it's hard for me to see. I have an NMOS browser on my laptop and I can see the presenter's output as an NMOS device. I'd like to connect to the presenter's sender and see the video on my laptop.

Can I connect to that endpoint using my app and watch it on my Laptop's display, provided that I have I'm an authenticated user on the network with appropriate permissions to access the resources? If I'm allowed to access the resources sometimes, but not at other times (like during a speaker's presentation), how does that access get revoked or constrained when it is being used? What's to stop my connection from causing the source to reset its display to accommodate me and where does that policy get set?

Because these connections are dynamic and multiple controllers have access to NMOS devices, I see a need for something to represent the "media presentation context" (a place holder name) so that control over the presentation is clear and can be clearly deleted/released when the user says that it's over, independent of a Flow's existence. I see this as the base for, or an extension of, the IS-XX API / IPMX Device Control Resource in the current architecture.

### Some loose notes on a "media presentation context" (MPC) resource

> **Note**: There might be no need for a "media presentation context", or maybe there is another way to bring order to a system where there is foreseeable potential for multiple controllers from multiple vendors to create connections with devices. This is all IMHO, I'm open to other ideas, and I don't wish to bloat the scope of this activity. I think there is a balance between keeping within the lines of the activity and recognizing the system and domain context of the activity. People may disagree on where and when these decisions should be made.

An MPC resource:

* May be created by a System Controller to represent a presentation session between a source and 0..n receivers, independent of any Flows, provided the Sender is not currently captured by an existing MPC.
* Acts as the context/session for the sender and connected receivers, encapsulating them. 
* Has the URIs of Sender and all Receivers.
* Connection requests sent directly to the Sender or connected Receivers that did not come from this resource would be redirected to this resource, which could carry out the request, keeping the state consistent.
* Can be nested. MPC may be encapsulated by parent MPCs. (see following paragraph)
* May have a direct connection (IS-07/WebSocket/etc) with each receiver and the sender
* Receives and transmits events to receivers and senders
* Contains timing information (source clock, epoch, grain rate), current profile, and other information related to the presentation.
* Aggregates Receiver Capabilities and has logic to reduce them to one set from the aggregate (XOR) (could forward be handled by a parent NPC)
* Can limit the number of connected receivers (and express those limits), e.g. HDCP requirements
* Is deleted when the connection is done, independent of any Flows.
* Can receive other connection/flow-related events and properties (out of scope): stream received, packets dropped and other errors, latency between sender and receiver, etc.

#### Nesting

The implementation of this resource might be in the System Controller or could be in the device. If the device and the System Controller both implement an MPC resource, then the System Controller can encapsulate the device's MPC under its own, effectively limiting it to receiving requests only from the System Controller. That is, the device is captured by its own MPC, which is captured by the System Controller's MPC. In this way, a central controller could *always* encapsulate a device. Also, the System controller *may* allow other controllers to encapsulate this MPC, or it may not, depending on the configuration.

There might be other applications for this sort of nesting (out of scope), especially when there are processing devices in between. The idea is to create a very general context/session mechanism to support what we need for our narrow use cases, and others.

**Comment by andrewstarks** [comment] 2021-03-04 00:44
> HDCP Support uin described in the EDID. To be confirmed in the EDID spec we will refer to? Not seen

HDCP existence is not in the EDID payload. It is a separate register over the same I2C bus (in HDMI) and there is a protocol for discovering its existence. While it is not in the EDID payload, it's possible that we might want to consider it to be within scope, as it is part of the Destination's properties/capabilities. We may also decide to extend this API later, when we tackle support for EDID.

**Comment by andrewstarks** [comment] 2021-03-04 00:49
>Should it have additional EDID fields or the whole EDID?

We should have an end point for the raw EDID, to cover improperly formed EDID data/debugging, and data not included in Receiver Capabilities.

I also think that we should do what is essential to create flows in this activity and define how manufacturers may include more EDID information, if desired. The goal should be interoperability and potentially the ability to round-trip EDID data, as much as it makes sense to do that.

**Comment by prince-chrismc** [comment] 2021-03-10 23:00
### Is the notation of changing a Sender's flow where the problems originates from?

Building on the Use Case describe above...

1. We have a _spreadsheet_ (the green) on the presentation screen

![image](https://user-images.githubusercontent.com/16867443/110705654-b37fc380-81c4-11eb-8f5b-c383eb2e901d.png)

#### Proposed Architecture 

> as per my understanding of it

2. A Laptop joins the flow to have a better view of the text 🔎 
    * The Sender automatically adjusts because...
       a. the separate layer of control override the previous configuration (_easy to avoid since the sender says which it has_)
       b. the IS-XX obtained two (or a second) `media-essentials` and the picture is the lowest common factor

![image](https://user-images.githubusercontent.com/16867443/110706014-34d75600-81c5-11eb-9ab0-83d3fe87fcbf.png)

❓ Could the sender refuse the new media essentials in any case? Let's say [`409`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409)

#### Presently there are fixed Senders/Flow/Source combination that can not be controlled

> via an IS-XX

2. A Laptop joins the flow (the yellow-gold)
    * The Receiver automatically adjust (coverts?) because it was told to capture something that was not supported
    * the receiver rejects the command because it was told to capture something that was not supported

![image](https://user-images.githubusercontent.com/16867443/110707281-15412d00-81c7-11eb-890b-8efc6206f28a.png)

***

➡️ How closely do we need to recreate the mechanics of a baseband connection?

Can my DVD player always say "I am doing 1080p60 w/ HDR!" and pick the Receiver that capable of doing that?
If there must be connection, we could change the sender _explicitly_ but this would still break unknown connection... which is already a problem we have yet to solve.

**Closed as completed** 2021-04-22 14:21 UTC
